### ISSUE TITLE
Problem: slow queries can slow down consensus state machine

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1007]
__Proposal:__ Make the query runs concurrently with the consensus state machine

__Current behavior:__ slow queries can block consensus execution and cause the node to lag behind,

__Desired behavior:__ Query should be handled concurrently with consensus.

__Use case:__

Fix the lag behind issue in RPC nodes.

**Comment by yihuang** [comment]
https://github.com/cosmos/cosmos-sdk/pull/10997
could use grpc client to query.

**Comment by adu-crypto** [comment]
it seems concurrent grpc gatewy is solved by this [PR](https://github.com/cosmos/cosmos-sdk/pull/11234)?


> Current grpc happens to be concurrent, while the grpc gateway itself is not, since it always uses abci query. Therefore, as the current queries are not concurrent, throughput has the room for improvement. This PR changes the grpc gateway so that when server is ran by a node daemon, it directly calls grpc to make queries concurrent. Any services that uses grpc gateway could improve throughput by fundamental amount, which has been tested and ensured in the process of running an Osmosis node using the current chagnes.

**Comment by yihuang** [comment]
> it seems concurrent grpc gatewy is solved by this [PR](https://github.com/cosmos/cosmos-sdk/pull/11234)?
> 
> 
> 
> 
> 
> > Current grpc happens to be concurrent, while the grpc gateway itself is not, since it always uses abci query. Therefore, as the current queries are not concurrent, throughput has the room for improvement. This PR changes the grpc gateway so that when server is ran by a node daemon, it directly calls grpc to make queries concurrent. Any services that uses grpc gateway could improve throughput by fundamental amount, which has been tested and ensured in the process of running an Osmosis node using the current chagnes.
> 
> 
> 
> 

Yeah, but ethermint json-rpc don't use the grpc apis directly, but through the abci client
