### ISSUE TITLE
Store tx hash index separately to get rid of full tendermint tx indexes

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1075]
__Proposal:__ Store tx hash index separately to get rid of full tendermint tx indexes

__Current behavior:__

rely on full nodes to turn on tendermint tx indexer, cost extra storage space, and slow down consensus state machine.

__Desired behavior:__

- Use a standalone kv db to store eth tx hash -> cosmos tx hash.
- The eth tx hash index will include all the eth msgs in the block, no matter the execution result.
- Support the unlucky tx that exceeds block gas limit into the json-rpc apis, since user fee is deducted in this case, it should leave a trace in json-rpc responses.

__Use case:__

- Reduce storage cost, because the db size increase fast. https://github.com/crypto-org-chain/cronos/issues/451#issuecomment-1115918818
- Support some failed transactions in json-rpc responses.

**Comment by yihuang** [comment]
This will also solve the failed tx hash not found issue. https://github.com/tharsis/ethermint/pull/1062

**Comment by fedekunze** [comment]
I feel that we should we try to prioritize the modular hasher ADR: https://github.com/tendermint/tendermint/issues/6539

**Comment by JayT106** [comment]
> > I feel that we should we try to prioritize the modular hasher ADR: [tendermint/tendermint#6539](https://github.com/tendermint/tendermint/issues/6539). Any other solution will involve additional maintenance and overhead
> 
> Can modular hash handle multiples messages(eth tx) in one tm tx?

From the Tendermint dev's decision, they would prefer to do it in ABCI++ during `prepareproposal `.

https://github.com/tendermint/tendermint/pull/8033/files#diff-d4c2afdd9920a19ba459ab66bb2ffa4e732447831618f6e8777e811314ef76e7R155

**Comment by yihuang** [comment]
https://github.com/crypto-org-chain/cronos/issues/451#issuecomment-1118131006

BTW, there's an option to fine turn what events to index, we can use that to shrink the tx indexer db size, so db size is less of a motivation for this proposal.

The other potential motivation is to cover more tx than tm tx indexer, this may also be solved by emit a eth tx hash event at the beginning of ante handlers for eth tx.

**Comment by tomtau** [comment]
One more motivation is not having the the indexer affected by unrelated tm issues that may take some time to diagnose and fix: https://github.com/tendermint/tendermint/issues/5281

**Comment by yihuang** [comment]
I think we can implement this extra indexer as an optional feature, like if the extra indexer is not initialized, the json-rpc can fallback to exist logic.

**Comment by yihuang** [comment]
By doing a reindexing for the old blocks, we can deprecate some old json-rpc fallback logic which is ugly and inefficient:
https://github.com/tharsis/ethermint/blob/main/rpc/namespaces/ethereum/eth/api.go#L904

**Comment by yihuang** [comment]
unstale.
