### ISSUE TITLE
Users can't sign Metamask txs with high `MinGasPrice`

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#1134]
## Problem

The new `MinGasPrices` parameter on testnet was set to the same value that we decided for mainnet, i.e `25,000,000,000`. Because the difference is so high with the base fee on testnet (currently has a value of 7), the difference needs to be added in the priority tip field (in the case of EIP-1559 tx). The main issue is that the Metamask UI restricts this behavior by disabling the Send button when PriorityTip >>> BaseFee .

## Possible Solution: Use `MinGasPrices` as minimum bound for `BaseFee`

We can use the `MinGasPrices` param to set a minimum bound of the BaseFee when [calculating](https://github.com/tharsis/ethermint/blob/main/x/feemarket/keeper/eip1559.go#L16) the BaseFee in EndBlock:

This could look something like this: 

```
nextBaseFee = Max(BaseFee, params.MinGasPrice)
```

With this solution, we have a parameter that sets an absolute bound, that can be controlled by governance, while the need of compensation the difference between  `BaseFee` and `MinGasPrices` through the `PriorityFee`

What do you think? Do you have other solutions?

**Comment by danburck** [comment]
@loredanacirstea What's your opinion on this?

**Comment by loredanacirstea** [comment]
As long as this bounded `BaseFee` value is accounted for in the fee history RPC endpoint, this approach seems like the best solution.

**Comment by Goldmindsx** [comment]
> ## Problem
> The new `MinGasPrices` parameter on testnet was set to the same value that we decided for mainnet, i.e `25,000,000,000`. Because the difference is so high with the base fee on testnet (currently has a value of 7), the difference needs to be added in the priority tip field (in the case of EIP-1559 tx). The main issue is that the Metamask UI restricts this behavior by disabling the Send button when PriorityTip >>> BaseFee .
> 
> ## Possible Solution: Use `MinGasPrices` as minimum bound for `BaseFee`
> We can use the `MinGasPrices` param to set a minimum bound of the BaseFee when [calculating](https://github.com/tharsis/ethermint/blob/main/x/feemarket/keeper/eip1559.go#L16) the BaseFee in EndBlock:
> 
> This could look something like this:
> 
> ```
> nextBaseFee = Max(BaseFee, params.MinGasPrice)
> ```
> 
> With this solution, we have a parameter that sets an absolute bound, that can be controlled by governance, while the need of compensation the difference between `BaseFee` and `MinGasPrices` through the `PriorityFee`
> 
> What do you think? Do you have other solutions?

Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/
