### ISSUE TITLE
With pruning, cosmos block query works, but eth_getBlockByNumber fails

### ISSUE THREAD

**Issue by SeKim12** [evmos/ethermint#1146]
## Summary of Bug
When pruning option is set, querying for blocks past pruning height is possible with cosmos. However, they are inaccessible via ethereum JSON-RPC methods, e.g. `eth_getBlockByNumber`

From my understanding, pruning configurations pertain to application state, so I would have assumed block data to persist (as it does for cosmos queries). I'm not too sure what would be different for rpc. 

This may just be from my lack of understanding of when/how/what states are pruned. Would really appreciate some enlightenment!

## Steps to Reproduce
    ./evmosd start --keyring-backend test --pruning=custom --pruning-interval=10  --json-rpc.api eth,txpool,personal,net,debug,web3,miner
    
    # properly gets block at height 1
    ./evmosd query block 1

    # but when using json-rpc endpoint
    curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}' -H "Content-Type: application/json" http://localhost:8545

    # I get the following response:
    {
        "jsonrpc": "2.0",
        "id": 1,
        "error": {
        "code": -32000,
        "message": "rpc error: code = Unknown desc = UnmarshalJSON cannot decode empty bytes: panic"
        }
    }

## Additional context
I've been looking at `x/evm` in ethermint, and this may be something...: 
The function `EthBlockFromTm` calls `BlockResults` (in tm) to get ABCI results at a given height, to ensure consistency. 
This in turn calls `LoadFinalizeBlockResponses()`, which is a tm State Store method. Maybe as the State Store is pruned, the results aren't properly being retrieved? 

Really appreciate the help! 
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Goldmindsx** [comment]
> ## Summary of Bug
> When pruning option is set, querying for blocks past pruning height is possible with cosmos. However, they are inaccessible via ethereum JSON-RPC methods, e.g. `eth_getBlockByNumber`
> 
> From my understanding, pruning configurations pertain to application state, so I would have assumed block data to persist (as it does for cosmos queries). I'm not too sure what would be different for rpc.
> 
> This may just be from my lack of understanding of when/how/what states are pruned. Would really appreciate some enlightenment!
> 
> ## Version
> ## Steps to Reproduce
> ```
> ./evmosd start --keyring-backend test --pruning=custom --pruning-interval=10  --json-rpc.api eth,txpool,personal,net,debug,web3,miner
> 
> # properly gets block at height 1
> ./evmosd query block 1
> 
> # but when using json-rpc endpoint
> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}' -H "Content-Type: application/json" http://localhost:8545
> 
> # I get the following response:
> {
>     "jsonrpc": "2.0",
>     "id": 1,
>     "error": {
>     "code": -32000,
>     "message": "rpc error: code = Unknown desc = UnmarshalJSON cannot decode empty bytes: panic"
>     }
> }
> ```
> 
> ## Screenshots
> ## Additional context
> I've been looking at `x/evm` in ethermint, and this may be something...: The function `EthBlockFromTm` calls `BlockResults` (in tm) to get ABCI results at a given height, to ensure consistency. This in turn calls `LoadFinalizeBlockResponses()`, which is a tm State Store method. Maybe as the State Store is pruned, the results aren't properly being retrieved?
> 
> Really appreciate the help!
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/
