### ISSUE TITLE
Docs for ethermint PubKey not correct?

### ISSUE THREAD

**Issue by webmaster128** [evmos/ethermint#1158]
In https://github.com/evmos/ethermint/blob/main/proto/ethermint/crypto/v1/ethsecp256k1/keys.proto we have

```
// PubKey defines a type alias for an ecdsa.PublicKey that implements
// Tendermint's PubKey interface. It represents the 33-byte compressed public
// key format.
```

But isn't the whole purpose of the type to store an uncompressed 65 byte pubkey?

**Comment by Goldmindsx** [comment]
> In https://github.com/evmos/ethermint/blob/main/proto/ethermint/crypto/v1/ethsecp256k1/keys.proto we have
> 
> ```
> // PubKey defines a type alias for an ecdsa.PublicKey that implements
> // Tendermint's PubKey interface. It represents the 33-byte compressed public
> // key format.
> ```
> 
> But isn't the whole purpose of the type to store an uncompressed 65 byte pubkey?


Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/
