### ISSUE TITLE
Problem: traceTransaction always returns success for simple transfer tx

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1185]
__System info:__ ethermint main

__Steps to reproduce:__

In a batch tx, a simple transfer eth tx could fail, in which case, traceTransaction will return success after https://github.com/evmos/ethermint/pull/1159

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by Goldmindsx** [comment]
> **System info:** ethermint main
> 
> **Steps to reproduce:**
> 
> In a batch tx, a simple transfer eth tx could fail, in which case, traceTransaction will return success after #1159
> 
> **Expected behavior:** [What you expected to happen]
> 
> **Actual behavior:** [What actually happened]
> 
> **Additional info:** [Include gist of relevant config, logs, etc.]


Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/

**Comment by yihuang** [comment]
I see ibc relayers are pushing for support of concurrent nonce, there's also up-coming app-side mempool support, in which we could possibly support future-list, with those features, we can stop supporting the batch eth tx feature, then stop worry about this issue ;D
