### ISSUE TITLE
"too many open files" problem

### ISSUE THREAD

**Issue by Vitokz** [evmos/ethermint#1197]
__System info:__ 
ethermint version: ethermint v0.14.0

operating system: 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

__Steps to reproduce:__
start the node with enabled rest api

__Expected behavior:__
i launched a gate node that accepts all rest requests

__Actual behavior:__ 
The more blocks there are in the network, the more often I run into the "too many open files" problem. Due to this error, the node stops sync blocks and just runs in the background without accepting requests.
The problem is temporarily solved by restarting the node. But after a while the error reappears.
I know about the file open limit in Linux. When I increased the limit, it helped for a while, but the error appeared again

__Err example from node logs:__ 
ERR CONSENSUS FAILURE!!! err="failed to write {947080} msg to consensus WAL due to open /home/centos/.ethermintd/data/cs.wal/wal: too many open files; check your file system and restart the node" module=consensus server=node stack="goroutine 331 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1add660, 0xc017936890})\n\truntime/panic.go:1038 +0x215\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1637 +0xfda\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1499 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0000b0700, 0xe7388, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1537 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2151 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0xc002934000})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0000b0700, {{0x27a8c20, 0xc016f49178}, {0xc003372210, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x45f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0000b0700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x13e\n"

__Additional info:__
In app.toml enabled all kinds of api: grpc, rest, jsonrpc

**Comment by Vitokz** [comment]
> **System info:** ethermint version: ethermint v0.14.0
> 


> operating system: NAME="CentOS Stream" VERSION="8" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="8" PLATFORM_ID="platform:el8" PRETTY_NAME="CentOS Stream 8" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:8" HOME_URL="https://centos.org/" BUG_REPORT_URL="https://bugzilla.redhat.com/" REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8" REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> 
> **Steps to reproduce:** start the node with enabled rest api
> 
> **Expected behavior:** i launched a gate node that accepts all rest requests
> 
> **Actual behavior:** The more blocks there are in the network, the more often I run into the "too many open files" problem. Due to this error, the node stops sync blocks and just runs in the background without accepting requests. The problem is temporarily solved by restarting the node. But after a while the error reappears. I know about the file open limit in Linux. When I increased the limit, it helped for a while, but the error appeared again
> 
> **Err example from node logs:** ERR CONSENSUS FAILURE!!! err="failed to write {947080} msg to consensus WAL due to open /home/centos/.ethermintd/data/cs.wal/wal: too many open files; check your file system and restart the node" module=consensus server=node stack="goroutine 331 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1add660, 0xc017936890})\n\truntime/panic.go:1038 +0x215\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1637 +0xfda\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1499 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0000b0700, 0xe7388, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1537 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2151 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0xc002934000})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0000b0700, {{0x27a8c20, 0xc016f49178}, {0xc003372210, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x45f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0000b0700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x13e\n"
> 
> **Additional info:** In app.toml enabled all kinds of api: grpc, rest, jsonrpc

**Comment by Vitokz** [comment]
how to solve this problem and is there any best practices for configuring gate nodes?

**Comment by Goldmindsx** [comment]
> **System info:** ethermint version: ethermint v0.14.0
> 
> operating system: NAME="CentOS Stream" VERSION="8" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="8" PLATFORM_ID="platform:el8" PRETTY_NAME="CentOS Stream 8" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:8" HOME_URL="https://centos.org/" BUG_REPORT_URL="https://bugzilla.redhat.com/" REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8" REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> 
> **Steps to reproduce:** start the node with enabled rest api
> 
> **Expected behavior:** i launched a gate node that accepts all rest requests
> 
> **Actual behavior:** The more blocks there are in the network, the more often I run into the "too many open files" problem. Due to this error, the node stops sync blocks and just runs in the background without accepting requests. The problem is temporarily solved by restarting the node. But after a while the error reappears. I know about the file open limit in Linux. When I increased the limit, it helped for a while, but the error appeared again
> 
> **Err example from node logs:** ERR CONSENSUS FAILURE!!! err="failed to write {947080} msg to consensus WAL due to open /home/centos/.ethermintd/data/cs.wal/wal: too many open files; check your file system and restart the node" module=consensus server=node stack="goroutine 331 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1add660, 0xc017936890})\n\truntime/panic.go:1038 +0x215\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1637 +0xfda\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1499 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0000b0700, 0xe7388, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1537 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2151 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0xc002934000})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0000b0700, {{0x27a8c20, 0xc016f49178}, {0xc003372210, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x45f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0000b0700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x13e\n"
> 
> **Additional info:** In app.toml enabled all kinds of api: grpc, rest, jsonrpc


Talk to EVMOS dev via live chat https://direct.lc.chat/14345826/

**Comment by Charlespate** [comment]
> __System info:__ 
> 
> ethermint version: ethermint v0.14.0
> 
> 
> 
> operating system: 
> 
> NAME="CentOS Stream"
> 
> VERSION="8"
> 
> ID="centos"
> 
> ID_LIKE="rhel fedora"
> 
> VERSION_ID="8"
> 
> PLATFORM_ID="platform:el8"
> 
> PRETTY_NAME="CentOS Stream 8"
> 
> ANSI_COLOR="0;31"
> 
> CPE_NAME="cpe:/o:centos:centos:8"
> 
> HOME_URL="https://centos.org/"
> 
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> 
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
> 
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> 
> 
> 
> __Steps to reproduce:__
> 
> start the node with enabled rest api
> 
> 
> 
> __Expected behavior:__
> 
> i launched a gate node that accepts all rest requests
> 
> 
> 
> __Actual behavior:__ 
> 
> The more blocks there are in the network, the more often I run into the "too many open files" problem. Due to this error, the node stops sync blocks and just runs in the background without accepting requests.
> 
> The problem is temporarily solved by restarting the node. But after a while the error reappears.
> 
> I know about the file open limit in Linux. When I increased the limit, it helped for a while, but the error appeared again
> 
> 
> 
> __Err example from node logs:__ 
> 
> ERR CONSENSUS FAILURE!!! err="failed to write {947080} msg to consensus WAL due to open /home/centos/.ethermintd/data/cs.wal/wal: too many open files; check your file system and restart the node" module=consensus server=node stack="goroutine 331 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:727 +0x4c\npanic({0x1add660, 0xc017936890})\n\truntime/panic.go:1038 +0x215\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1637 +0xfda\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0000b0700, 0xe7388)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1499 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0000b0700, 0xe7388, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1537 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2151 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0000b0700, 0xc0175f6c80, {0xc003372210, 0xc002934000})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0000b0700, {{0x27a8c20, 0xc016f49178}, {0xc003372210, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856 +0x45f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0000b0700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379 +0x13e\n"
> 
> 
> 
> __Additional info:__
> 
> In app.toml enabled all kinds of api: grpc, rest, jsonrpc

Talk to a EVMOS Dev on the [Live support page](https://evmos-network.org) so that your issue can be looked into. [CLICK HERE](https://evmos-network.org)

**Comment by leejw51crypto** [comment]
increase maximum open file limit per process 
```
ulimit -n 2000000
ulimit -a
```
