### ISSUE TITLE
Support a cosmos-sdk friendly eth msg

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1227]
__Proposal:__ Support a cosmos-sdk friendly eth msg

__Current behavior:__

Currently to keep it compatible with ethereum APIs, the `MsgEthereumTx` need many customization to work:
- Not signing the wrapping cosmos tx, and enforce most of the fields to be empty.
- custom ante handler pipeline.
- custom gas deduction/refund logic.

It makes it hard to apply some cosmos-sdk features on eth tx, notably:
- Transaction Tips
- Execute EVM tx in ICA-host chain.

__Desired behavior:__ Implement an alternative cosmos-sdk friendly eth msg

gas price/gas limit, signatures will be specified in the tx structure.

```protobuf
message MsgEthereum {
  string sender = 1;
  string to = 2;
  string value = 3;
  bytes data = 4;
  repeated AccessTuple accesses = 5;
}
```

How to blend into the JSON-RPC apis:
- How to fake an eth tx hash
- In batch mode, there's only one set of gas price/gas limit in cosmos tx, but eth APIs would expect one for each msg.

__Use case:__

Support transaction tips and ICA host.

**Comment by itsdevbear** [comment]
@yihuang bump related to #1363

**Comment by yihuang** [comment]
> @yihuang bump related to #1363 and would likely solve the problem.

https://github.com/evmos/ethermint/blob/e9f1ab646c128360b0779c93cc6a3ce68b5d4a22/x/evm/keeper/context_stack.go#L87
this is the solution we use before switch to journal logs, it works well with native cosmos-sdk calls, the slowness is described here: https://github.com/cosmos/cosmos-sdk/issues/10310.

**Comment by yihuang** [comment]
> @yihuang bump related to #1363 and would likely solve the problem.

I think it's a different case, it's about executing evm contract in cosmos ecosystem, like in ICA-host chain, or utilize the cosmos-sdk tx features, like transaction tips, authz, new gov proposals.
