### ISSUE TITLE
Documenting the new tx indexer

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1235]
__Proposal:__ Documenting the new tx indexer

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by yihuang** [comment]
Forgot this, will do

**Comment by VictorTrustyDev** [comment]
Up

**Comment by VictorTrustyDev** [comment]
Up
