### ISSUE TITLE
Best practices when running JSON-RPC service

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#1243]
A huge part of why the JSON-RPC has been unreliable is the lack of documentation for infrastructure providers and node operators. We should add more documentation on how to run the JSON-RPC regarding:

- Node configuration for JSON-RPC
- Namespaces
- Pruning settings
- Indexing, etc

Ref:  https://docs.evmos.org/developers/json-rpc/running_server.html

**Comment by facs95** [comment]
Closed by this https://github.com/evmos/evmos/pull/863
