### ISSUE TITLE
Create Event Router for EVM tx post processing

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#1244]
# Context

## Problem 1: Efficiency and Performance

Currently, all the modules that implement the EVM hooks run the post processing hook. This is true even when they handle a completely event that was emitted in the transaction logs, they run the hook. This is redundant and severely impacts the performance of EVM transactions. 

## Problem 2: Isolating errors

Part of the cause from the EVM incident, was that an error from the ERC20 module affected modules and part of the stack that was completely unrelated. This caused all the EVM transactions to fail. See [EVM postmortem](https://hackmd.io/@fedekunze/ryJLSwizq) for details.

Isolating errors to a single event type or module, will prevent other modules from being affected by unrelated error handling mistakes.

## Proposal

Implement a Router mechanism like the one in the IBC module in order to route specific events to the registered modules that handle those events.

**Comment by danburck** [comment]
@facs95 we moved it back to Todo, since there is no draft PR yet. Is there any work done here already?

**Comment by GAtom22** [comment]
[Braindump doc](https://www.notion.so/evmos/EVM-Hooks-Refactor-1c0c23dd9d8349f0a99e8990a28b115c) with analysis and ideas
