### ISSUE TITLE
JSON RPC "invalid chain id for signer" error

### ISSUE THREAD

**Issue by facs95** [evmos/ethermint#1266]
When the node doesn't receive new blocks, we cannot use the debug_traceTransaction method in RPC. 

Client (blockscout) error: 

`May 24 19:11:20 blockscout cosmovisor[140643]: 7:11PM INF Served eth_getTransactionReceipt conn=10.128.0.19:49852 duration=3.399659 err="invalid chain id for signer" module=geth reqid=80"
`

Server error: 

`evmosd[5014]: t=2022-08-11T16:15:11+0000 lvl=warn msg="Served debug_traceTransaction"    conn=192.168.64.2:34000   reqid=3   t=24.934867ms              err="rpc error: code = Unknown desc = rpc error: code = Internal desc = invalid chain id for signer: unknown request
`

**Comment by VictorTrustyDev** [comment]
Chain ID only be set in 2 places within evm module
- BeginBlock in abci.go
- InitGenesis in genesis.go
So I guess when node doesn't receive new blocks, the BeginBlock wasn't called thus k.eip155ChainID always default zero value and caused this issue
