### ISSUE TITLE
WS subscriptions ending prematurely

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#1280]
This code might have a bug which breaks websocket subscriptions: https://github.com/tharsis/ethermint/blob/main/rpc/websockets.go#L184

You need to replace return with continue because it breaks the infinite loop, which is deregister all subscription. via defer function. It's not a trivial issue, I event ran it in playground: https://go.dev/play/p/X5GvQYlC69h

Would be also good to add error logging here: https://github.com/tharsis/ethermint/blob/main/rpc/websockets.go#L182
So we may try to find the reason of abnormal disconnection for a single customer.

**Comment by danburck** [comment]
transferring comment from @facs95 
I have been looking deeper into this and I think more thought has to be put into how to to solve it. This error is expected to break the loop as its descriptions mentions 
```

// Applications must break out of the application's read loop when this method
// returns a non-nil error value. Errors returned from this method are
// permanent. Once this method returns a non-nil error, all subsequent calls to
// this method return the same error.
func (c *Conn) NextReader() (messageType int, r io.Reader, err error) {
```

This is on hold until our nodes are upgrade with the latest binary that has an extra log to get more information of whats going on

**Comment by faddat** [comment]
I've a good deal of evidence that this isn't happening in our code and may be related to proxy configuration.

**Comment by facs95** [comment]
Closing this given @faddat comment

**Comment by JoowonYun** [comment]
> I've a good deal of evidence that this isn't happening in our code and may be related to proxy configuration.
> 
> Since I have live test endpoints, please send a ping in slack and I can send the endpoints over to you.

Hi @faddat, can you give me some information about the evidence?
I'm configuring a network with 1 node locally, and websocket's deadline exceeds. I'm not sure what the problem is.

**Comment by zakir-code** [comment]
Maybe try setting readWait to 0.

https://github.com/evmos/ethermint/blob/292fe03b2d1811360f3297ed81bb088a432a04e8/server/util.go#L77
