### ISSUE TITLE
Support evmc interface

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1310]
__Proposal:__ Support evmc interface

https://github.com/ethereum/evmc

__Current behavior:__ only support go-ethereum evm implementation

__Desired behavior:__ Through evmc interface to support alternative high-performance EVM implementations.

__Use case:__ Improve EVM performance.

Requests may be closed if we're not actively planning to work on them.

**Comment by itsdevbear** [comment]
We may be able to support here, have been drafting this internally.

**Comment by fedekunze** [comment]
note, we don't have the capacity to work on this feature at this point in time. Open for external contributions
