### ISSUE TITLE
Unneeded creation of new acc when funds are insufficient?

### ISSUE THREAD

**Issue by randy75828** [evmos/ethermint#1322]
![image](https://user-images.githubusercontent.com/44086461/188121609-1602e7cb-251d-4d62-b127-0c4321688d95.png)

Found these lines of code in eth.go under EthAccountVerificationDecorator. 
Was thinking if this is pointless? If account is not present, no transaction can be done? So why bother creating a new account? it will fail line 132 check anyway. Perhaps someone could enlighten me on this?

**Comment by VictorBerryy** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)

**Comment by VictorBerryy** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)
