### ISSUE TITLE
cosmos-sdk `--grpc-only` is not integrated in start cmd

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1359]
__Proposal:__ Integrate `--grpc-only` flag in start cmd

__Current behavior:__ don't support grpc only mode

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
what's the problem context for this?

**Comment by VictorTrustyDev** [comment]
This is the purpose of the `--grpc-only` flag: [cosmos-sdk#10796](https://github.com/cosmos/cosmos-sdk/issues/10796)

**Comment by VictorTrustyDev** [comment]
Perhaps he doesn't want new upgrades effect the historical data querying process.

Like this [#1242](https://github.com/evmos/ethermint/issues/1242), the new module make we unable to call old blocks due to nil params.

**Comment by yihuang** [comment]
> what's the problem context for this?

We are planing a feature of distributed query service by replicating the chain state directly, which should be less costly than just running multiple full nodes. In this setup, we only have one full node and multiple read-only replicates which serve grpc query service only.
