### ISSUE TITLE
Problem: coinbase should not be the current one in traceTransaction execution

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1391]
__System info:__ ethermint main

__Steps to reproduce:__

In `EVMConfig`, the coinbase address is always fetched based on current context `ctx.BlockHeader().ProposerAddress`, which will be the current check state, aka. the last committed block's proposer address, in grpc-only mode, it would be an empty one.
But in `traceTransaction`, or `eth_call` with historical height, it should be the proposer of respective block.

__Expected behavior:__ coinbase should be the correct one when executing historical transactions.

__Actual behavior:__ is either the latest one or empty.

__Additional info:__

Solution: find the proposer address in json-rpc through tendermint api, and pass explicitly to grpc query handler.

**Comment by VictorTrustyDev** [comment]
Will also resolve [this #1269](https://github.com/evmos/ethermint/issues/1269)

**Comment by yihuang** [comment]
> Will also resolve [this #1269](https://github.com/evmos/ethermint/issues/1269)

yeah, I guess this is the root cause of that.
