### ISSUE TITLE
Problem: chainID is not initialized under grpc only mode

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1404]
__System info:__ ethermint main

__Steps to reproduce:__

1. start a grpc only node
2. call `TraceTx` through `debug_traceTransaction`.
3. it complains: `invalid chain id for signer`

__Expected behavior:__ traceTransaction should work

__Actual behavior:__ the chain id in the evm keeper is not initialized without abci event.

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by yihuang** [comment]
Basically, in grpc query, we can't reply on `ctx` for anything other than the block height, because those are either not initialized, or don't match the block we are processing, we need to pass them through the request, json-rpc service can fill them with information from the block header.

**Comment by VictorTrustyDev** [comment]
This can be resolved by sending blockHeader proto the same as send proposerAddress like the fix you did few days ago. It contains both chain id and proposerAddress so actually we can replace the proposerAddress field with blockHeader field

**Comment by yihuang** [comment]
yeah, or adding a chain-id field to some requests that needed, because different grpc queries need different fields in the header.

**Comment by VictorTrustyDev** [comment]
proposer address and chain id are all problems I got while developing my product until now. Seems no longer any un-expected issue like this would happens in the future
