### ISSUE TITLE
Address CodeQL warnings

### ISSUE THREAD

**Issue by fedekunze** [evmos/ethermint#1421]
Address warnings reported by the [CodeQL](https://github.com/evmos/ethermint/security/code-scanning?query=is%3Aopen+branch%3Amain+tool%3ACodeQL) tool

**Comment by VictorTrustyDev** [comment]
Is the link broken or not accessible by everyone? I got 404

**Comment by MalteHerrmann** [comment]
@fedekunze I think this can be closed right? For the current state on `main` all CodeQL checks run flawlessly:

https://github.com/evmos/ethermint/actions/runs/3848739767/jobs/6556900836
