### ISSUE TITLE
feegrant not work with evm raw tx

### ISSUE THREAD

**Issue by piotr-sikora-v** [evmos/ethermint#1443]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

Ethermint commit: 5759e72ccbb98610a72aba1f8a98c50669415a04
OS: Ubuntu 22.04 LTS

__Steps to reproduce:__

1/ `ethermintd tx feegrant grant ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d ethm1s2tu3ltgp9te22r0epg7dtaw52yk0x7d3w6laj --from mykey --spend-limit 30000000000000000aphoton  --chain-id=ethermint_9010-1 --gas=300000 --gas-prices=10aphoton`
2/ `ethermintd  tx evm raw $ETHRAWTX --from=testfee --chain-id=ethermint_9010-1 --gas=300000 --gas-prices=10aphoton --log_level trace  --fee-granter ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d`
__Expected behavior:__ [What you expected to happen]
Send EthereumTX

__Actual behavior:__ [What actually happened]
raw_log: 'failed to check sender balance: sender balance < tx cost (0 < 3000000000000000):
  insufficient funds'

__Additional info:__ [Include gist of relevant config, logs, etc.]
After I add balance to this account, raw tx send normal but fee is take from ethm1s2tu3ltgp9te22r0epg7dtaw52yk0x7d3w6laj instend of ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d

**Comment by piotr-sikora-v** [comment]
@VictorTrustyDev 
```
- address: ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d
  name: mykey
- address: ethm1s2tu3ltgp9te22r0epg7dtaw52yk0x7d3w6laj
  name: testfee
```
transaction others than `evm` works greate with same parameters

**Comment by vincentysc** [comment]
Hello, I am also trying the feegrant module with EVM tx. I have a question on it. 

How to show the `feeGranter` on EVM level ? EVM level is assuming that the `from` is the fee payer.

**Comment by VictorTrustyDev** [comment]
Sorry, my bad, I missed your previous tag @piotr-sikora-v but I also have no idea why.

But I feel something weird, as you wrote
```text
Actual behavior: [What actually happened]
raw_log: 'failed to check sender balance: sender balance < tx cost (0 < 3000000000000000):
insufficient funds'
```
so the `ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d` akka `mykey` does not have balance, how the first tx `tx feegrant grant` could be completed?

**Comment by piotr-sikora-v** [comment]
@VictorTrustyDev this raw_log error is strange for me too couse `ethm1ma7lkftdppqxk6ca2mtck5w3xtzzjkznukcg8d` have about `60600806700056512173288` aphoton

feegrant for me only don't work with `tx evm raw`  ... all others modules works greate...
I will try same thing on evmos but I have some problem with evmos faucet testnet

But main question for me is... this should work with EVM module?
I want to give feegrants to user that will interact with smartcontracts

**Comment by VictorTrustyDev** [comment]
Idk
Hi @MalteHerrmann, sorry to bother you but is the fee-grant works in this case?

**Comment by MalteHerrmann** [comment]
> I will try same thing on evmos but I have some problem with evmos faucet testnet

@piotr-sikora-v if you give me your testnet address I can send you some tokens.

@VictorTrustyDev I'll test this and get back here

**Comment by piotr-sikora-v** [comment]
@MalteHerrmann ethm13weegf8wgm28wqmqv769w8wnztzktxxym5elw8
Thanks in advanced!

**Comment by MalteHerrmann** [comment]
> ethm13weegf8wgm28wqmqv769w8wnztzktxxym5elw8

I thought you wanted Evmos testnet tokens? I need an Evmos address then

**Comment by piotr-sikora-v** [comment]
> > ethm13weegf8wgm28wqmqv769w8wnztzktxxym5elw8
> 
> I thought you wanted Evmos testnet tokens? I need an Evmos address then

sorry... my bad
evmos1s08e6rzmyee2huhcwg9wetzv9f9u7a30rweqc2

**Comment by jacobhjkim** [comment]
Hey @MalteHerrmann, did you have a chance to test feegrant with EVM transactions?

**Comment by MalteHerrmann** [comment]
@jacobhjkim I was not yet, sorry!

**Comment by jacobhjkim** [comment]
Hi @MalteHerrmann,

It seems like Ethermint does not support `x/feegrant` by design. Here is an error message which says that fee payer and fee granted should be empty for eth tx.
https://github.com/evmos/ethermint/blob/1a2ee06d15b66d5b88a30b4dc4ea63d8ff00a179/app/ante/setup.go#L144

I can't find any reasoning behind not allowing the `x/feegrant` module to be used with Ethermint. Especially when evm tx flag includes `--fee-granter` and `--fee-payer`.

```
$ ./ethermintd tx evm raw -h

Build cosmos transaction from raw ethereum transaction

Usage:
  ethermintd tx evm raw TX_HEX [flags]

Flags:
...
      --fee-granter string       Fee granter grants fees for the transaction
      --fee-payer string         Fee payer pays fees for the transaction instead of deducting from the signer
...
```

Can I open a PR which allows `x/feegrant` module to be used with Ethermint?

**Comment by piotr-sikora-v** [comment]
@jacobhjkim Hi,
I just tested your path, and is something wrong.
On account where I added grant , when I send transaction with `--fee-granter` and `--fee-payer` from other accout I recive some extra founds ;)
exactly 1500000000000000000aphoton on every transaction
and  also is too much taken from graneer
look:
Grantee is ethm1mrstz5cumaaars33zck0vqwqy736k4gdm3xhqp
Granter is ethm1azw825ec03xktrv9qvnyzrcjg9vetk705uvuzm

Before send balances:

``` $ ethermintd q bank balances ethm1mrstz5cumaaars33zck0vqwqy736k4gdm3xhqp
- balances:
  amount: "1500000000021000"
  denom: aphoton
pagination:
  next_key: null
  total: "0"
$ ethermintd q bank balances ethm1azw825ec03xktrv9qvnyzrcjg9vetk705uvuzm
- balances:
  amount: "99997999996999999976000000"
  denom: aphoton
pagination:
  next_key: null
  total: "0" 
```

next... I sending singed raw transaction (only do something on smartcontract)

`ethermintd tx evm raw $ETHRAWTX --from=acc1 --gas=30000 --gas-prices=10aphoton --log_level trace --fee-granter ethm1azw825ec03xktrv9qvnyzrcjg9vetk705uvuzm  --fee-payer ethm1azw825ec03xktrv9qvnyzrcjg9vetk705uvuzm  --keyring-backend test `

balances after that:
```
$ ethermintd q bank balances ethm1mrstz5cumaaars33zck0vqwqy736k4gdm3xhqp
balances:
- amount: "3000000000021000"
  denom: aphoton
pagination:
  next_key: null
  total: "0"
$ ethermintd q bank balances ethm1azw825ec03xktrv9qvnyzrcjg9vetk705uvuzm
balances:
- amount: "99997999993999999976000000"
  denom: aphoton
pagination:
  next_key: null
  total: "0"
```

**Comment by jacobhjkim** [comment]
Hi @facs95 @danburck @piotr-sikora-v, I think there are two ways to go about this issue.

First, we can somehow modify `flags.AddTxFlagsToCmd(cmd)` to not include `--fee-granter` and `--fee-payer`.
https://github.com/evmos/ethermint/blob/1a2ee06d15b66d5b88a30b4dc4ea63d8ff00a179/x/evm/client/cli/tx.go#L124

Another way is to properly implement the `x/feegrant` feature to Ethermint, which I am willing to contribute.

What do you guys think?

**Comment by piotr-sikora-v** [comment]
@jacobhjkim It will be awesome to implement this feature to ethermint.
I can help you with testing.
