### ISSUE TITLE
Upload proto files to buf.build/evmos/ethermint

### ISSUE THREAD

**Issue by MalteHerrmann** [evmos/ethermint#1468]
In reference to [#1466](https://github.com/evmos/ethermint/pull/1466)

## Description

In order for the Protobuf scripts on the Evmos side to use the Ethermint `.proto`s without storing them as `third_party` data in the Evmos repo, it is necessary to upload them to [buf.build/evmos/ethermint](https://buf.build/evmos/ethermint).

As a reference, here are the cosmos-sdk proto files on that page, which the Ethermint repo itself is using: [buf.build/cosmos](https://buf.build/cosmos)

**Comment by fedekunze** [comment]
this is now done
