### ISSUE TITLE
Json RPC[8545] does not work after v0.19.3: "err="rpc error: code = Unavailable desc = connection closed before server preface received" 

### ISSUE THREAD

**Issue by FletcherMan** [evmos/ethermint#1523]
__System info: 
After release version of v.19.3(not included), including v0.20.0-rc1, v0.20.0-rc2, branch of 'main'

__Steps to reproduce: 
```
1. git clone https://github.com/evmos/ethermint.git
2. git checkout v0.20.0-rc2
3. sh init.sh

## after node is started

4. curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x....","latest"],"id":67}' localhost:8545

{"jsonrpc":"2.0","id":67,"error":{"code":-32000,"message":"rpc error: code = Unavailable desc = connection closed before server preface received"}}
```

__Expected behavior: 
{"jsonrpc":"2.0","id":67,"result":"0x52b79ca6fe5f0d05600000"}

__Actual behavior:
{"jsonrpc":"2.0","id":67,"error":{"code":-32000,"message":"rpc error: code = Unavailable desc = connection closed before server preface received"}}

__Additional info:
if I checkout the main branch, the Error looks more detail. It was like 
'{"jsonrpc":"2.0","id":67,"error":{"code":-32000,"message":"rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\""}}'

Error log from node: 
INF Served eth_blockNumber conn=[::1]:62984 duration=0.553143 err="rpc error: code = Unavailable desc = connection error: desc = \"**_error reading server preface: http2: frame too large_**\"" module=geth reqid=4832370929353076

**Comment by dreamer-zq** [comment]
Hello,How did you solve it?
