### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by cisan86** [evmos/ethermint#1524]
__System info:__ 
i run it on ubuntu 18

__Steps to reproduce:__
1. git clone 
2. make install
3. sudo docker-compose up

__Actual behavior:__
[+] Running 0/4
 ⠿ ethermintdnode3 Error                                                                                                                                              3.5s
 ⠿ ethermintdnode1 Error                                                                                                                                              3.5s
 ⠿ ethermintdnode0 Error                                                                                                                                              3.5s
 ⠿ ethermintdnode2 Error                                                                                                                                              3.5s
Error response from daemon: pull access denied for ethermintd/node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by poiug07vsys** [comment]
You should build image before using it

**Comment by 4rgon4ut** [comment]
Hey @cisan86, `docker-compose` file rely on prebuilded images and basically used in make command `localnet-start`

```make
# Build image for a local testnet
localnet-build:
	@$(MAKE) -C networks/local

# Start a 4-node testnet locally
localnet-start: localnet-stop
ifeq ($(OS),Windows_NT)
	mkdir localnet-setup &
	@$(MAKE) localnet-build

	IF not exist "build/node0/$(ETHERMINT_BINARY)/config/genesis.json" docker run --rm -v $(CURDIR)/build\ethermint\Z ethermintd/node "./ethermintd testnet --v 4 -o /ethermint --keyring-backend=test --ip-addresses ethermintdnode0,ethermintdnode1,ethermintdnode2,ethermintdnode3"
	docker-compose up -d
else
	mkdir -p localnet-setup
	@$(MAKE) localnet-build

	if ! [ -f localnet-setup/node0/$(ETHERMINT_BINARY)/config/genesis.json ]; then docker run --rm -v $(CURDIR)/localnet-setup:/ethermint:Z ethermintd/node "./ethermintd testnet --v 4 -o /ethermint --keyring-backend=test --ip-addresses ethermintdnode0,ethermintdnode1,ethermintdnode2,ethermintdnode3"; fi
	docker-compose up -d
endif
```

If you need to setup localnet, use `make localnet-start` or you can prebuild image with `-t ethermintd/node` flag with desired version of ethermint.
