### ISSUE TITLE
AllowUnprotectedTxs of JSONRPCConfig parameter is not valid

### ISSUE THREAD

**Issue by wangchao0222** [evmos/ethermint#1540]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
i run it on mac

__Steps to reproduce:__

1. set allow-unprotected-txs=true
2. start the server 
3. commit unprotected-tx of ethereum

__Expected behavior:__ [What you expected to happen]
accept the unprotected-tx

__Actual behavior:__ [What actually happened]
the server reject the tx

__Additional info:__ [Include gist of relevant config, logs, etc.]
i read the file of server/config/config.go find that the function of GetConfig(v *viper.Viper) (Config, error) not read allow-unprotected-txs config from viper
so the allow-unprotected-txs config is not valid

**Comment by fedekunze** [comment]
the `allow-unprotected-txs` flag is for local node configuration and should only be used when the on-chain parameter is set to `true`. The default parameter value is set to `false`, so the behavior is the expected one

**Comment by wangchao0222** [comment]
if I want set the AllowUnprotectedTxs parameter value to true，I need to change the code of ‘GetConfig(v *viper.Viper) (Config, error)’

like this :
JSONRPC: JSONRPCConfig{
			Enable:              v.GetBool("json-rpc.enable"),
			API:                 v.GetStringSlice("json-rpc.api"),
			Address:             v.GetString("json-rpc.address"),
			WsAddress:           v.GetString("json-rpc.ws-address"),
			GasCap:              v.GetUint64("json-rpc.gas-cap"),
			FilterCap:           v.GetInt32("json-rpc.filter-cap"),
			FeeHistoryCap:       v.GetInt32("json-rpc.feehistory-cap"),
			TxFeeCap:            v.GetFloat64("json-rpc.txfee-cap"),
			EVMTimeout:          v.GetDuration("json-rpc.evm-timeout"),
			LogsCap:             v.GetInt32("json-rpc.logs-cap"),
			BlockRangeCap:       v.GetInt32("json-rpc.block-range-cap"),
			HTTPTimeout:         v.GetDuration("json-rpc.http-timeout"),
			HTTPIdleTimeout:     v.GetDuration("json-rpc.http-idle-timeout"),
			**AllowUnprotectedTxs: v.GetBool("allow-unprotected-txs"),**
			MaxOpenConnections:  v.GetInt("json-rpc.max-open-connections"),
			EnableIndexer:       v.GetBool("json-rpc.enable-indexer"),
			MetricsAddress:      v.GetString("json-rpc.metrics-address"),
		},

**Comment by wangchao0222** [comment]
add the code : AllowUnprotectedTxs: v.GetBool("allow-unprotected-txs")
