### ISSUE TITLE
JSON RPC method `eth_feeHistory` returns 1 less item in `baseFeePerGas`

### ISSUE THREAD

**Issue by macong-cdc** [evmos/ethermint#1559]
__System info:__

__Steps to reproduce:__

```shell
curl --location --request POST 'https://eth.bd.evmos.org:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [
        4,
        "latest",
        null
    ],
    "id": 0
}'
```

__Expected behavior:__
5 items should be in `baseFeePerGas` in the response as mentioned [here](https://web3py.readthedocs.io/en/stable/web3.eth.html?highlight=verify_eth_getProof#web3.eth.Eth.fee_history).

```
This includes the next block after the newest of the returned range, because this value can be derived from the newest block.
```

__Actual behavior:__
4 items in `baseFeePerGas`
```
{"jsonrpc":"2.0","id":0,"result":{"baseFeePerGas":["0x4a817c800","0x4a817c800","0x4a817c800","0x4a817c800"],"gasUsedRatio":[0.016875,0.003654575,0,0.00144495],"oldestBlock":"0x83e77a"}}
```

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by ramacarlucho** [comment]
You are missing an optional param, which is required to obtain the `reward` response.
The query should look like this
```
curl --location --request POST 'https://eth.bd.evmos.org:8545' --header 'Content-Type: application/json' --data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [
        4,
        "latest",
        [10,90]
    ],
    "id": 0
}'
```

So the response is 
```
{"jsonrpc":"2.0","id":0,"result":{"baseFeePerGas":["0x4a817c800","0x4a817c800","0x4a817c800","0x4a817c800"],"gasUsedRatio":[0.00137325,0.0065864,0,0.00332595],"oldestBlock":"0x84075f","reward":[["0x59682f00","0x59682f00"],["0x0","0x0"],["0x0","0x0"],["0x0","0x0"]]}}
```

**Comment by macong-cdc** [comment]
@ramacarlucho 
I am not talking about `reward` in the response, I am talking about **number of items in `baseFeePerGas`** in the response.

As mentioned in the [documentation](https://web3py.readthedocs.io/en/stable/web3.eth.html?highlight=verify_eth_getProof#web3.eth.Eth.fee_history), with `block_count` input of **4**, **5** items are expected in `baseFeePerGas`.

```
>>> w3.eth.fee_history(4, 'latest', [10, 90])
AttributeDict({
    'oldestBlock': 3,
    'reward': [[220, 7145389], [1000000, 6000213], [550, 550], [125, 12345678]],
    'baseFeePerGas': [202583058, 177634473, 155594425, 136217133, 119442408],
    'gasUsedRatio': [0.007390479689642084, 0.0036988514889990873, 0.0018512333048507866, 0.00741217041320997]
})
```

However, for ethermint, with an input of 4, 4 items are returned in `baseFeePerGas`.
