### ISSUE TITLE
wrong status and gas in debug_traceTransaction

### ISSUE THREAD

**Issue by mmsqe** [evmos/ethermint#1583]
__System info:__ [main] branch

__Steps to reproduce:__

trace success [tnx](https://testnet.cronoscan.com/tx/0x91d9569bdc6e2a18dbda03601baa45b081307c7b8c07b772c7e7bf6f0892f8db) in testnet:
`curl --location --request POST 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": [
        "0x91d9569bdc6e2a18dbda03601baa45b081307c7b8c07b772c7e7bf6f0892f8db"
    ],
    "id": 1
}'`

__Expected behavior:__ 
should get `"failed": false, "gas": 135101`, and when pass with `callTracer` should get [refund](https://gist.github.com/mmsqe/1c8ff3df648c0735ccf2b398a0343293#file-0x91d9569bdc6e2a18dbda03601baa45b081307c7b8c07b772c7e7bf6f0892f8db-tracer-json-L83) value without error

__Actual behavior:__ 
get `"failed": true, "gas": 163914`, and when pass with `callTracer` get `"out of gas"` error

__Additional info:__ 
1. balance change from tendermint [events](https://gist.github.com/mmsqe/d13026c9f066ea877c3353d2f08c86c1):
`69667484395521009792-819570000000000000-14252689574316697128+82631294701814623+144065000000000000=54821921115906127287`
aligned with `69667484395521009792-14252689574316697128-135101*5000000000000+82631294701814623=54821921115906127287`

2. to align old tnx trace result need cache back access list within same block related to https://github.com/evmos/ethermint/issues/801

**Comment by VictorTrustyDev** [comment]
Well, I have just checked escan database of evmos main-net and got the `out of gas` plus `insufficient balance for transfer` in following blocks
| Height | Tx | Err |
| --- | --- | --- |
| 6927929 | 0xdf9fc05619464f859a16d3844c31ae709de7291b8685cca9d04fdba47dbda6f0 | insufficient balance for transfer |
| 912446 |  0x6359e8cc804d0a5e19f33a277a816c700842f6d5310d9a3d1a0053079a491724 | out of gas |
| 597825 |  0xe0b8f9f57dedf44c9923a91e302b265d60b34ab65ea3696b70cabd25f11851f3 | insufficient balance for transfer |
| 564897 |  0xf758b8296252a490f7821cefa058a203b10bd1679b28c494e8c644b6ebe569b1 | insufficient balance for transfer |
| 517040 |  0x00eaf3d3201e650f78ed8015b448eb88ee9300a9341038d0360f350214d4b6b4 | insufficient balance for transfer |
| 500379 |  0xfbce9d73c859fd9784f0023bbd94ab0f59f234e61d53cf8bfbedf654387d6401 | insufficient balance for transfer |
| 472360 |  0xefe75df6d94188a0440c7ec902b57fff6db98f12a55c4be758804963ad364ec0 | insufficient balance for transfer |
| 471898 |  0xe7be02d336f754c24066d59f9236b50bfce84c2ffad2d5b4ffa2a1a17cae05cd | out of gas |
| 386044 |  0x30899d6f47b7439a58585037ad112c2381542da55c4c64021e1c214ce24c49f4 | insufficient balance for transfer |
| 189139 |  0x833838a407f1480dbec9b1b49d1fe81c45bb10cd52e681f162d99820a21577b3 | out of gas |
| 179303 |  0x45ee974b08e3264b09fb0fa7e682a4e1c99b95a048684130040898acd7b1819a | insufficient balance for transfer |
| 120690 |  0x0417fefc2ff00dd007a2e7f723ffea609d8c59be9a8329fa167a665daf9258b9 | insufficient balance for transfer |
| 92026 |   0xadc4be5e0e3f62d6d9017da39f4a19a2211c048b63fd600bdeeb1a560e92b93d | insufficient balance for transfer |

**Comment by mmsqe** [comment]
> Well, I have just checked escan database of evmos main-net and got the `out of gas` plus `insufficient balance for transfer` in following blocks

Thanks, do you have any url that I can call with `debug_traceTransaction` or any equivalent page ([success](https://testnet.cronoscan.com/tx/0x4701127eb111d32d89fc7b989887c7eef5c314c8f8b1e7e0b6651b5dff594031#internal) vs [fail](https://testnet.cronoscan.com/tx/0x91d9569bdc6e2a18dbda03601baa45b081307c7b8c07b772c7e7bf6f0892f8db#internal) refund) shows the trace result?

**Comment by VictorTrustyDev** [comment]
@mmsqe VictorTrustyDev#2801 DM me please
