### ISSUE TITLE
Problem: typed event change breaks the json-rpc queries

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1594]
__System info:__ ethermint main

__Steps to reproduce:__

Recent typed event refactoring  (https://github.com/evmos/ethermint/pull/1544) didn't update json-rpc and tx indexer accordingly.

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by Vvaradinov** [comment]
The changes were reverted for now to unblock current PRs. Will come back to the TypedEvents at a later stage.
