### ISSUE TITLE
EIP712 error when IBC timeout-height = 0

### ISSUE THREAD

**Issue by giansalex** [evmos/ethermint#1644]
__System info:__ 
- `evmos/ethermint@v0.21.0`
- `evmos/evmos@v11.0.0`

__Steps to reproduce:__

1. Connect with Metamask or Ledger
2. Send  an IBC transfer with timeout timestamp and set timeout-height 0-0 

__Expected behavior:__ 
Successful IBC transfer with timestamp as timeout

__Actual behavior:__ 
Error using JS
```
there is extra data provided in the message (6 < 7): unauthorized.
```
Error ledger+CLI
```
Error: unable to generate EIP-712 hash for object: there is extra data provided in the message (6 < 7)
```

__Additional info:__ 
`timeout-height 0-0` works when using Proto Msg

**Comment by EricGat1** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)

**Comment by giansalex** [comment]
the error is still present in version v12

**Comment by giansalex** [comment]
No
