### ISSUE TITLE
Unknown transactions

### ISSUE THREAD

**Issue by maoaixiao1314** [evmos/ethermint#1652]
I have a problem. A transaction we don't know transfers all tokens to this address:0x123456f6Ed06F81eb1Edc6fccE34414E2C21fE5c
Run ethermint:
ethermint start
                    --home /data/.treasurenetd 
                    --keyring-backend file 
                    --json-rpc.api eth,txpool,personal,net,debug,web3,miner 
                    --pruning=nothing --trace
  --json-rpc.address uses the default address "0.0.0.0:8545". due to this reason? If so, how to configure the correct address     
![1675221231060](https://user-images.githubusercontent.com/39184323/215936353-4f3385e4-301d-4e45-b25e-b6feab0e87af.png)

The transaction is displayed in the explorer, but the blockchain reports an error: failed to check sender balance: sender balance<tx cost

**Comment by ongrid** [comment]
We experienced the same issue witin our setup with the same target address 0x123456...

It seems, some kind of malicious scanner discovered your API. Then using personal API it discovered addresses and wiped them out using `personal_sendTransaction` call using 0x123456... for funds collection.

Consider removing `personal` from exposed `--json-rpc.api` to disallow such discovery and transfer.
