### ISSUE TITLE
Unstable eth websocket event subscriptions

### ISSUE THREAD

**Issue by CRossel87a** [evmos/ethermint#1745]
Hi,

I have re-produced this bug with Evmos, Cronos and Canto clients, and have found Ethermint to be the common factor.
For my app I use multiple long-duration event subscriptions to newheads and topics. **It is a consistent and provable problem across multiple versions, multiple binaries, multiple compiles (external, and my own).** It occurs both when the client has a dedicated server, and when it is shared with other clients. 

When a problem occurs, the clients will accept a new subscription and respond with a subscription id, but then not actually push any events. This problem will typically start occurring after running for 2-6 hours. It also seems like the problem occurs more frequently when event activity on-chain is lower. Re-connecting to the client on every 2minute time-outs do not solve the problem. Only a forced client restart will do it.

One temporary fix I have used is to program a periodic restart of the clients every 2-3h. That seems to "minimize the damage". 

## Steps to Reproduce

New blocks:
wscat -c ws://127.0.0.1:8546
{"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params":["newHeads"]}

For Uniswap2 Sync events:
wscat -c ws://127.0.0.1:8546
{"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params": ["logs", {"topics": ["0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"]}]}

**Comment by CRossel87a** [comment]
Hi,

ref. https://github.com/evmos/evmos/releases/tag/v12.1.2

This did not solve the problem

**Comment by CRossel87a** [comment]
Public Evmos RPC websocket server is broken. Does not emit all Uniswap2 sync events:

wscat -c wss://eth.bd.evmos.org:8546
{"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params": ["logs", {"topics": ["0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"]}]}

**Comment by mmsqe** [comment]
> {"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params": ["logs", {"topics": ["0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"]}]}

I can't reproduce yet, may I ask its events are delay or no new events at all?
<img width="1178" alt="Screenshot 2023-04-27 at 11 14 08 AM" src="https://user-images.githubusercontent.com/2867936/234750590-c37dec72-e6d0-4c6b-9ea0-95378968c3f6.png">

**Comment by CRossel87a** [comment]
I have been able to break the

> {"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params": ["logs", {"topics": ["0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"]}]}

I had not been subbing to the public RPC lately. So I think you waited too long to try this. If you open up 2-3 multiple concurrent subscriptions the public rpc will break after a few hours

**Comment by mmsqe** [comment]
May I ask if there's event received after reconnect? If yes, it would be subscription issue in client side. If no, it would be websocket issue in server side.

**Comment by CRossel87a** [comment]
> 

Upon re-connect while "broken" you can send the eth_subscribe, and you will obtain a receipt subscription id in response. So the connection is working fine. However, after obtaining the receipt id, you will not get any further logs pushed into the channel

**Comment by CRossel87a** [comment]
> May I ask if there's event received after reconnect? If yes, it would be subscription issue in client side. If no, it would be websocket issue in server side.

Upon re-connect while "broken" you can send the eth_subscribe, and you will obtain a receipt subscription id in response. So the connection is working fine. However, after obtaining the receipt id, you will not get any further logs pushed into the channel

**Comment by CRossel87a** [comment]
> 

The lack of events after confirmed subscription id is replicated across multiple listning software, such as direct wscat query, or with Python websockets or Rust tokio tungstenite. I am 100% certain this issue is server side. Remember that this error only occurs after an hour or more of polling. Typically a node restart will help for a period.

**Comment by CRossel87a** [comment]
I went to log level 'error' and got these:

May 09 13:47:09 v2202211186789206564 cantod[10998]: 1:47PM ERR failed to add event topic to event bus error="topic already registered" api=websocket-server module=websocket-client topic="tm.event='Tx' AND message.module='evm'"


May 09 13:54:17 v2202211186789206564 cantod[11161]: 1:54PM ERR failed to add event topic to event bus error="topic already registered" api=websocket-server module=websocket-client topic="tm.event='Tx' AND message.module='evm'"

After these errors, no more events were pushed out

**Comment by VictorTrustyDev** [comment]
I think you found the correct error message

In `filter_system.go`
```go
ch := make(chan coretypes.ResultEvent)
es.topicChans[f.event] = ch
if err := es.eventBus.AddTopic(f.event, ch); err != nil {
    es.logger.Error("failed to add event topic to event bus", "topic", f.event, "error", err.Error())
}
```

Look, `es.topicChans[f.event]` got replaced by new `chan ch`.
I think flow should be `AddTopic` first, if success, replace it.

Just few comments, I'll let someone else implement if my guess is correct.

**Comment by CRossel87a** [comment]
> 

Great! Hope that it's. I am currently debugging on my Canto node which is running an older version. It seems newheads subscription work while logs do not, so the problem is likely isolated to topic subscriptions

**Comment by mmsqe** [comment]
@CRossel87a May I ask the steps to verify not solved?

**Comment by CRossel87a** [comment]
> @CRossel87a May I ask the steps to verify not solved?

@mmsqe Same steps as described above. However, I think the reason you have not been able to re-produce it is because it seems to happen if you have a program that is attempting to create multiple subscriptions at the same time, such as when an app attempts to subscribe to 3 topics at once over 3 separate connections. I am now attempting to add time between subscriptions to see if this produces stability

**Comment by VictorTrustyDev** [comment]
How about also adding `es.index[][]=f` onto the `else` block?

**Comment by CRossel87a** [comment]
> Or backup existing (if any) then restore in case of `err != nil`

I am a bit out of my element with Golang :) Just hacking around

**Comment by mmsqe** [comment]
> > @CRossel87a May I ask the steps to verify not solved?
> 
> @mmsqe Same steps as described above. However, I think the reason you have not been able to re-produce it is because it seems to happen if you have a program that is attempting to create multiple subscriptions at the same time, such as when an app attempts to subscribe to 3 topics at once over 3 separate connections. I am now attempting to add time between subscriptions to see if this produces stability. Testing a hypothesis that there is some multi-threaded collision

If channel get changed somewhere when concurrent subscribe happens, your fix should work. I'll try add some test for it

**Comment by DefiDebauchery** [comment]
Maybe I’m misunderstanding the context of the last few messages, but just want to be sure to note that this bug shouldn’t have anything to do with a collision on concurrent subscriptions. Just a single subscribe will fail after a time.

**Comment by CRossel87a** [comment]
@mmsqe @VictorTrustyDev I think we have the solution! Persistent and stable websocket event subscription for two days running

**Comment by VictorTrustyDev** [comment]
Nice, how was the fix?
