### ISSUE TITLE
The readme file needs maintenance

### ISSUE THREAD

**Issue by cisan86** [evmos/ethermint#1846]
__System info:__  There are two issues with this readme doc that I hope you can resolve:

**No1.**
Installation section, `please read the Evmos [Installation](https://docs.evmos.org/validators/quickstart/installation.html) instructions.`
the Hyperlink is broken

**No2.**
Quick Start section, `go to the [Introduction](https://docs.evmos.org/about/intro/overview.html) ` 
the Hyperlink is broken

**Comment by MalteHerrmann** [comment]
We are not maintaining Ethermint anymore. All updated info can be found in the [Evmos repository](https://github.com/evmos/evmos).
