### ISSUE TITLE
should not use cosmos-sdk/simapp as a library

### ISSUE THREAD

**Issue by panda8z** [evmos/ethermint#1855]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

## ERRORs
```
go: nft-index/service imports
        github.com/evmos/ethermint/x/evm/types tested by
        github.com/evmos/ethermint/x/evm/types.test imports
        github.com/evmos/ethermint/app imports
        github.com/cosmos/cosmos-sdk/simapp: github.com/cosmos/cosmos-sdk/simapp@v0.0.0-20230921091541-2efafee65653: parsing go.mod:
        module declares its path as: cosmossdk.io/simapp
                but was required as: github.com/cosmos/cosmos-sdk/simapp
```
__Steps to reproduce:__

1. [First Step] use this version in your go.mod `github.com/cosmos/cosmos-sdk v0.47.5
	github.com/evmos/ethermint v0.22.0`
2. [Second Step] `go mod tidy` 
3. [and so on...] you can get the **ERRORs**

__Expected behavior:__ [What you expected to happen]

we should delete the simapp in ethermint

__Actual behavior:__ [What actually happened]

there is using the simapp in `https://github.com/evmos/ethermint/blob/main/app/app.go` line 44 45 etc

__Additional info:__ [Include gist of relevant config, logs, etc.]

and Why we should remove all simapp depend on ? pls read this issue: [github.com/cosmos/cosmos-sdk/issues/15912](https://github.com/cosmos/cosmos-sdk/issues/15912)

**Comment by MalteHerrmann** [comment]
Ethermint does not support Cosmos SDK v0.47.x. It is also now deprecated. If you want to use the EVM module with SDK >0.47 refer to [Evmos](https://github.com/evmos/evmos).
