### ISSUE TITLE
EVM Revert and Out-of-gas error doesn't follow the correct format

### ISSUE THREAD

**Issue by yijiasu-crypto** [evmos/ethermint#314]
__System info:__ 
```
0.0.0-308-g7e1b45b
```

__Steps to reproduce:__

1. Make a out-of-gas eth_call
 * Can use: `yarn test --network ethermint proxy`
2. The `out-of-gas` error occured. However the JSON-RPC message is in a different format compared to `ganache`

__Expected behavior:__ [What you expected to happen]
```
 <   {
 <     "id": 1626419303744,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "VM Exception while processing transaction: out of gas",
 <       "code": -32000,
 <       "data": {
 <         "0xf08cc2bfa30270de3f28f2d8349d2797e9e15251c0cd8c2555b581c8428f2904": {
 <           "error": "out of gas",
 <           "program_counter": 219,
 <           "return": "0x"
 <         },
 <         "name": "c"
 <       }
 <     }
 <   }
```
__Actual behavior:__ [What actually happened]

```

 <   {
 <     "jsonrpc": "2.0",
 <     "id": 1626419644885,
 <     "error": {
 <       "code": -32000,
 <       "message": "out of gas"
 <     }
 <   }
```
__Additional info:__ [Include gist of relevant config, logs, etc.]

Since the out-of-gas error is correctly occured. But the returned message can't be parsed by truffle framework, returned in a test failed.

**Comment by leejw51crypto** [comment]
nice catch

**Comment by thomas-nguy** [comment]
linked to #247

**Comment by yijiasu-crypto** [comment]
To re-produce the error:

1. Start `ethermint` node on localhost. Listen on 8545
2. cd `tests/solidity/suites/proxy`
3. Run `yarn truffle test --network ethermint --verbose-rpc | grep "out of gas" -A 50 -B 50`
( You can omitted the `grep` part to inspect the full rpc logs. However it's very verbose and will output a lot)
4. The screen will not print anything for a while (1~2 mins). This is normal, since it has not started the execution of that problematic test case.
5. You can see something like this:
```
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_call",
   >   "params": [
   >     {
   >       "from": "0x90fdb51c13ce085ce7f9c0da8683b7327711b064",
   >       "gas": "0x5a0a",
   >       "gasPrice": "0x3b9aca00",
   >       "value": "0x64",
   >       "to": "0x260d4674b0b54f771d588cafdefd4bb7cfee280a"
   >     },
   >     "latest"
   >   ],
   >   "id": 1626855091441
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 1626855091441,
 <     "error": {
 <       "code": -32000,
 <       "message": "out of gas"
 <     }
 <   }
```

The log lines start with `>>>` means this is a request from truffle to ethermint, those start with `<<<` means it's a json-rpc response. Look at the `id`, every request will have an unique id and you could found its response followed by the request log.

**Comment by yijiasu-crypto** [comment]
You can stop the `ethermint` and run `ganache-cli` to listen on 8545 and re-run the test. Then you can see logs with legitimate error response.

To install `ganache-cli`: https://github.com/trufflesuite/ganache-cli

**Comment by fedekunze** [comment]
@thomas-nguy are you still working on this?

**Comment by thomas-nguy** [comment]
yes, I need to do more testing but I will open the PR soon

**Comment by thomas-nguy** [comment]
for 
```
 <       "data": {
 <         "0xf08cc2bfa30270de3f28f2d8349d2797e9e15251c0cd8c2555b581c8428f2904": {
 <           "error": "out of gas",
 <           "program_counter": 219,
 <           "return": "0x"
 <         },
 ```
 
 
 I wonder if it is not a specific implementation of ganache. I cannot find anything like that in geth
 @fedekunze  @yihuang ?

**Comment by yihuang** [comment]
https://github.com/ethereum/go-ethereum/blob/master/rpc/json.go#L109
all i can find is here, we might need to actually run it to check out the actual error message.

**Comment by yijiasu-crypto** [comment]
```
{
   "jsonrpc":"2.0",
   "id":1627577507785,
   "error":{
      "code":-32015,
      "data":"Out of gas",
      "message":"VM execution error."
   }
}
```

Here's the raw RPC response from Kovan

**Comment by yihuang** [comment]
I think it's fixed
