### ISSUE TITLE
Inconsistency between signature sign and verification

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#463]
__System info:__ ethermint main branch

By reading the code, I find that [`PrivKey.Sign`](https://github.com/tharsis/ethermint/blob/main/crypto/ethsecp256k1/ethsecp256k1.go#L110) only do Keccak hash when msg length is not 32, but in [`PubKey.VerifySignature`](https://github.com/tharsis/ethermint/blob/main/crypto/ethsecp256k1/ethsecp256k1.go#L205), there's no such check.

**Comment by leejw51crypto** [comment]
it's only activated when supplied bytes is not hash,
i think it's ok

**Comment by yihuang** [comment]
> it's only activated when supplied bytes is not hash,
> i think it's ok

but the signing logic need to match the verify logic, otherwise, verify will fail?

**Comment by leejw51crypto** [comment]
how about adding hash function  here?
if byte is not 32 length, hash with keccak
```
func (pubKey PubKey) VerifySignature(msg []byte, sig []byte) bool {
```

**Comment by leejw51crypto** [comment]
lie go-ethereum
```
func Sign(digestHash []byte, prv *ecdsa.PrivateKey) (sig []byte, err error) {
  if len(digestHash) != DigestLength {
    return nil, fmt.Errorf("hash is required to be exactly %d bytes (%d)", DigestLength, len(digestHash))
  }
  seckey := math.PaddedBigBytes(prv.D, prv.Params().BitSize/8)
  defer zeroBytes(seckey)
  return secp256k1.Sign(digestHash, seckey)
}
```

**Comment by leejw51crypto** [comment]
reject signing if byte is not already hashed , would be more solid

**Comment by leejw51crypto** [comment]
i'll submit pr shortly

**Comment by tomtau** [comment]
> Detecting need of hashing a message before signing
> KS-THA-O-03
> The function Sign checks if the input equals the length of the keccack256 output in order to determine if the message needs to be hashed or not prior to signing. This is not robust, as it can easily mistake unhashed messages for hashed ones, or input coming from different hash functions with similar bitsize, leading to interoperability issues.
> We recommend either assuming that the input is always hashed, as it is done in other libraries, or add a parameter to decide whether hashing is needed or not.

**Comment by yihuang** [comment]
This looks like a legitimate issue, didn't remember what happened to the original PR.
